/**
 * Photo / logo manifest, keyed by exact display name.
 * Generated by scripts/download-media.mjs — best-effort sourced images.
 * VERIFY each face/logo is correct; delete an entry to revert to the fallback.
 */
export const photoByName: Record<string, string> = {
  "Frank Noé": "/people/frank-noe.jpg",
  "Max Welling": "/people/max-welling.jpg",
  "Yu-Shan Lin": "/people/yu-shan-lin.jpg",
  "Heather J. Kulik": "/people/heather-kulik.png",
  "Ai Niitsu": "/people/ai-niitsu.jpg",
  "John Chodera": "/people/john-chodera.jpg",
  "Bruno Trentini": "/people/bruno-trentini.png",
  "Emine Kucukbenli": "/people/emine-kucukbenli.jpg",
  "Jigyasa Nigam": "/people/jigyasa-nigam.jpg",
  "Max Secor": "/people/max-secor.jpg",
  "Ole Winther": "/people/ole-winther.jpg",
  "Runzhong Wang": "/people/runzhong-wang.jpg",
  "Michael Bronstein": "/people/michael-bronstein.jpg",
  "Kristine Deibler": "/people/kristine-deibler.png",
  "Marwin Segler": "/people/marwin-segler.jpg",
  "Pranam Chatterjee": "/people/pranam-chatterjee.jpg",
  "Tejs Vegge": "/people/tejs-vegge.jpg",
  "Anthony Costa": "/people/anthony-costa.webp",
  "Konstantin Hemker": "/people/konstantin-hemker.jpg"
};

export const logoByName: Record<string, string> = {
  "NVIDIA": "/sponsors/nvidia.webp"
};

/** Official profile page per person (used by the profile dialog). */
export const profileByName: Record<string, string> = {
  "Frank Noé": "https://www.microsoft.com/en-us/research/people/franknoe/",
  "Max Welling": "http://amlab.science.uva.nl/people/MaxWelling/",
  "Yu-Shan Lin": "https://chem.tufts.edu/people/faculty/yu-shan-lin",
  "Heather J. Kulik": "https://chemistry.mit.edu/profile/heather-j-kulik/",
  "Ai Niitsu": "https://www.riken.jp/en/research/labs/ims/dyn_biomol_des/index.html",
  "John Chodera": "https://www.mskcc.org/research/ski/labs/john-chodera",
  "Bruno Trentini": "https://www.cs.ox.ac.uk/people/bruno.trentini/",
  "Emine Kucukbenli": "https://scholar.google.com/citations?user=LUXL9FoAAAAJ",
  "Jigyasa Nigam": "https://curiosity54.github.io/",
  "Max Secor": "https://scholar.google.com/citations?user=YiHfWhkAAAAJ",
  "Ole Winther": "https://olewinther.github.io/",
  "Runzhong Wang": "https://coley.mit.edu/people",
  "Michael Bronstein": "https://www.cs.ox.ac.uk/people/michael.bronstein/",
  "Marwin Segler": "https://www.microsoft.com/en-us/research/people/marwinsegler/",
  "Pranam Chatterjee": "https://directory.engineering.upenn.edu/pranam-chatterjee/",
  "Tejs Vegge": "https://www.dtu.dk/english/person/tejs-vegge?id=5334",
  "Konstantin Hemker": "https://www.cst.cam.ac.uk/people/kh701"
};

/** object-position overrides for off-centre source photos. */
export const objectPositionByName: Record<string, string> = {};
