#!/usr/bin/env node
/*
 * Download best-effort headshots / logos into /public and generate the media
 * manifest (src/content/media.ts). Only high/medium-confidence, real raster
 * images are saved; everything else falls back to initials / monogram.
 *
 *   node scripts/download-media.mjs /tmp/headshots.json
 *
 * Input JSON: { people: [{slug,name,imageUrl,confidence,sourcePage}], logo: {...} }
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const input = process.argv[2];
if (!input) {
  console.error("Usage: node scripts/download-media.mjs <results.json>");
  process.exit(1);
}
const data = JSON.parse(readFileSync(input, "utf8"));
const OK = new Set(["high", "medium"]);
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36";

mkdirSync("public/people", { recursive: true });
mkdirSync("public/sponsors", { recursive: true });

function sniff(buf) {
  if (buf[0] === 0xff && buf[1] === 0xd8) return "jpg";
  if (buf[0] === 0x89 && buf[1] === 0x50) return "png";
  if (buf.slice(0, 4).toString("latin1") === "RIFF" && buf.slice(8, 12).toString("latin1") === "WEBP")
    return "webp";
  return null;
}

async function download(url) {
  const res = await fetch(url, {
    headers: { "User-Agent": UA, Accept: "image/avif,image/webp,image/*,*/*" },
    redirect: "follow",
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length < 2500) throw new Error(`too small (${buf.length}b)`);
  if (buf.length > 6_000_000) throw new Error(`too large (${buf.length}b)`);
  const ext = sniff(buf);
  if (!ext) throw new Error(`not a raster image (${res.headers.get("content-type")})`);
  return { buf, ext };
}

const photo = {};
const logo = {};
const report = [];

for (const p of data.people ?? []) {
  if (!p.imageUrl || !OK.has(p.confidence)) {
    report.push(`  · ${p.name}: initials (${p.confidence || "none"})`);
    continue;
  }
  try {
    const { buf, ext } = await download(p.imageUrl);
    const file = `public/people/${p.slug}.${ext}`;
    writeFileSync(file, buf);
    photo[p.name] = `/people/${p.slug}.${ext}`;
    report.push(`  ✓ ${p.name}: ${p.slug}.${ext}  [${p.confidence}]  <- ${p.sourcePage || p.imageUrl}`);
  } catch (e) {
    report.push(`  ✗ ${p.name}: ${e.message} (kept initials)`);
  }
}

// Official profile links (from the headshot source page), excluding
// conference-aggregator / prior-role hosts that aren't a good "profile".
const PROFILE_DENY = ["convention.bio.org", "lab-of-the-future.com", "insights.bu.edu", "jclinic.mit.edu"];
const profile = {};
for (const p of data.people ?? []) {
  if (!p.sourcePage) continue;
  try {
    const host = new URL(p.sourcePage).host;
    if (PROFILE_DENY.some((d) => host.includes(d))) continue;
    profile[p.name] = p.sourcePage;
  } catch {
    /* ignore bad URL */
  }
}

// Per-face crop position overrides (some sourced images aren't head-centred).
const objectPosition = {
  "Heather J. Kulik": "50% 20%",
};

const lg = data.logo;
if (lg && lg.imageUrl && OK.has(lg.confidence)) {
  try {
    const { buf, ext } = await download(lg.imageUrl);
    writeFileSync(`public/sponsors/nvidia.${ext}`, buf);
    logo["NVIDIA"] = `/sponsors/nvidia.${ext}`;
    report.push(`  ✓ NVIDIA logo: nvidia.${ext}  <- ${lg.sourcePage || lg.imageUrl}`);
  } catch (e) {
    report.push(`  ✗ NVIDIA logo: ${e.message} (kept monogram)`);
  }
}

const manifest = `/**
 * Photo / logo manifest, keyed by exact display name.
 * Generated by scripts/download-media.mjs — best-effort sourced images.
 * VERIFY each face/logo is correct; delete an entry to revert to the fallback.
 */
export const photoByName: Record<string, string> = ${JSON.stringify(photo, null, 2)};

export const logoByName: Record<string, string> = ${JSON.stringify(logo, null, 2)};

/** Official profile page per person (used by the profile dialog). */
export const profileByName: Record<string, string> = ${JSON.stringify(profile, null, 2)};

/** object-position overrides for off-centre source photos. */
export const objectPositionByName: Record<string, string> = ${JSON.stringify(objectPosition, null, 2)};
`;
writeFileSync("src/content/media.ts", manifest);

console.log("\nMedia download report:");
console.log(report.join("\n"));
console.log(`\n✓ Saved ${Object.keys(photo).length} photos, ${Object.keys(logo).length} logos.`);
console.log("  Wrote src/content/media.ts — please verify each image is the right person.\n");
